spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: P8xRbVvgNIPfs1idLF3XDBP0fnCN7UDQ
            client-secret: gfAc5JmkgRWquyxHJSUSPG5QUNEoSwDUR3XOeNCWaLsRUXF4znBLJ47Zh-x_Hb68
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://bibliotecaxddiego.us.auth0.com/
